### ISSUE TITLE
Handle privacy 

### ISSUE THREAD

**Issue by rjnl** [rjnl/moodle-paygw_chargebee#1]
Use privacy provider

**Comment by danmarsden** [comment]
looks like privacy provider is only partially implemented?

you have completed the bare-minimum (metadata) but the export/delete components of the privacy api are not complete... I personally lean more towards the reject part of the fence for payment plugins on this - I think correct implementation of the privacy api is pretty important for plugins like this.

**Comment by danmarsden** [comment]
it also looks like this plugin passes the users name and email to chargebee which definitely should be covered in the privacy api under the get_external_link stuff:
https://moodledev.io/docs/apis/subsystems/privacy/#indicating-that-you-export-data-to-an-external-location

**Comment by rjnl** [comment]
Thanks Dan.
I'll update the privacy handling of the plugin.

**Comment by rjnl** [comment]
Fixed in https://github.com/rjnl/moodle-paygw_chargebee/commit/2792708cf292d4502380983bda5178865789f029
