### ISSUE TITLE
camel case in strings

### ISSUE THREAD

**Issue by danmarsden** [rjnl/moodle-paygw_chargebee#3]
https://github.com/rjnl/moodle-paygw_chargebee/blob/master/lang/en/paygw_chargebee.php#L40

Payment Methods -> Payment methods

-----
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

**Comment by rjnl** [comment]
Fixed: https://github.com/rjnl/moodle-paygw_chargebee/commit/72a136f2cd7f3ecdd9e4e54b93e0786022342943
