### ISSUE TITLE
verify_transaction 2 params or 4?

### ISSUE THREAD

**Issue by danmarsden** [rjnl/moodle-paygw_chargebee#4]
I'm only looking at this code in github, so I could be missing something but...

here:
https://github.com/rjnl/moodle-paygw_chargebee/blob/master/process.php#L49

you call it with 4 params, 

but here it's only defined as having 2 params:
https://github.com/rjnl/moodle-paygw_chargebee/blob/master/classes/chargebee_helper.php#L124

**Comment by rjnl** [comment]
Fixed: https://github.com/rjnl/moodle-paygw_chargebee/commit/37bb79c5f3fe01b5aef562f0a7886c94fa335beb
